[package]
name = "run-parts"
version = "0.1.0"
authors = ["Illya Kysil <ikysil@ikysil.name>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
